version: '3.9'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=Server=db,1433;Database=Holidays;User Id=sa;Password=Holiday12!
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  db:
    environment:
      SA_PASSWORD: "Holiday12!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 