version: '3.9'

services:
  api:
    container_name: holidays.api
    image: msiarko/holidays.api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=db,1433;Database=Holidays;User Id=sa;Password=Holiday12!
    build:
      context: .
      dockerfile: src/Holidays.API/Dockerfile
    depends_on: 
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: holidays.db
    environment:
      SA_PASSWORD: "Holiday12!"
      ACCEPT_EULA: "Y"
